module.exports = [{
  path: '/',
  component: 'Homepage',
  title: 'Overview',
  subtitle: '3 Elemental questions',
  description: 'Learn the Elemental step by step guide to interviewing. It includes real world strategies for each step of the job hiring process.',
  priority: '1.00',
  contentId: '71wUKRG4mZmkRGoXjZ1HRV',
}, {
  path: '/resume/',
  component: 'Resume',
  title: 'Résumé',
  subtitle: 'Create a great résumé',
  description: 'The Elemental résumé strategy is based on the 2 ways your résumé will be used.',
  priority: '0.80',
  contentId: '7CFF9HISMCxUry2sXEaZd1',
}, {
  path: '/phone-screen/',
  component: 'PhoneScreen',
  title: 'Phone Screen',
  subtitle: 'Verify your résumé',
  description: 'The Elemental strategy to pass phone screens is based on understanding the secret use of screens.',
  priority: '0.80',
  contentId: '5tX5uTI5USjO1GprBRFynh',
}, {
  path: '/interview/',
  component: 'Interview',
  title: 'Interview',
  subtitle: 'A simple trick to answer any question',
  description: 'The Elemental strategey for interviewing answers the 3 Elemental questions using easy to follow strategies of telling stories.',
  priority: '0.80',
  contentId: '2XJRl3PMtlSBM4lPC3AfzX',
}, {
  path: '/follow-up/',
  component: 'FollowUp',
  title: 'Follow Up',
  subtitle: 'A little goes a long way',
  description: 'The Elemental strategy realizes that following up doesn\'t need to be scary, it\'s actually a big plus.',
  priority: '0.80',
  contentId: '1DlG1BViOVuDDLBm9iXp5f',
}];